# Generated by Django 6.0.4 on 2026-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
    ]
