# Generated by Django 6.0.4 on 2026-04-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_ac_room_tv_room_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
