# Generated by Django 6.0.4 on 2026-04-13 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_image2_room_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=1, help_text='Number of guests'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='bathtub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Beds'), ('bunk', 'Bunk Beds')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='breakfast_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on the booking page', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, help_text='Floor number', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='room',
            name='jacuzzi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='minibar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating out of 5', max_digits=3),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, help_text='e.g. 101, 202A', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='safe',
            field=models.BooleanField(default=False, help_text='In-room safe box'),
        ),
        migrations.AddField(
            model_name='room',
            name='sea_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='size_sqm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Room size in square metres', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(help_text='Max number of guests'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per night', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('family', 'Family'), ('penthouse', 'Penthouse')], max_length=20),
        ),
    ]
