# Generated by Django 6.0.4 on 2026-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_guests_reservation_special_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe (Card)'), ('payhere', 'PayHere'), ('pay_at_hotel', 'Pay at Hotel')], default='pay_at_hotel', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pay_at_hotel', 'Pay at Hotel'), ('pending', 'Pending'), ('failed', 'Failed')], default='pay_at_hotel', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='size_sqm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
