# Generated by Django 6.0.4 on 2026-04-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_booking', 'New Booking'), ('cancelled', 'Booking Cancelled'), ('review', 'New Review'), ('test', 'Test')], default='new_booking', max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('guest', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
